version: '3'
services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./app:/app
    php:
        build:
            context: .
            dockerfile: PHP.Dockerfile
        volumes:
            - ./app:/app
    mysql:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: 'sander123'
            MYSQL_USER: 'webdeveloper'
            MYSQL_PASSWORD: 'sander123'
            MYSQL_DATABASE: 'webdevelopmentdb'
        volumes:
            - mysqldata:/var/lib/mysql
            - ./sql:/docker-entrypoint-initdb.d
        ports:
            - 3306:3306
    phpmyadmin:
        image: phpmyadmin:latest
        ports:
            - 8080:80
        environment:
            - PMA_HOST=mysql
        restart: unless-stopped
volumes:
    mysqldata: {}
